## Generic parameters used in analyzer
Generic:
    # choices: 'lepton+jet', 'dilepton', 'taus_lepton+jet', 'taus_dilepton'
    analysis_type: 'taus_lepton+jet'
    HLT_config_tag: 'HLT'
    filter_config_tag: 'PAT'
    verbosity: false
    # Prints events' triggers. Depends on verbosity and collect_trigger_stats
    print_HLT_event_path: false


## Triggers to fire upon
Triggers:
    # Performs unnecessary loops to collect all trigger data
    collect_trigger_stats: false
    ## Single lepton triggers:
    # List of single electron triggers.
    HLT_electron_triggers: [
'HLT_Ele27_eta2p1_WP85_Gsf_v1']
    # List of single muon triggers.
    HLT_muon_triggers: [
'HLT_IsoMu24_eta2p1_IterTrk02_v1']
    ## Dilepton triggers:
    # List of dielectron triggers. 
    HLT_electron_electron_triggers: [
'HLT_Ele23_Ele12_CaloId_TrackId_Iso_v1']
    # List of electron + muon triggers. 
    HLT_electron_muon_triggers: [
'HLT_Mu23_TrkIsoVVL_Ele12_Gsf_CaloId_TrackId_Iso_MediumWP_v1',
'HLT_Mu8_TrkIsoVVL_Ele23_Gsf_CaloId_TrackId_Iso_MediumWP_v1']
    # List of dimuon triggers. 
    HLT_muon_muon_triggers: [
'HLT_Mu30_TkMu11_v1',
'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_v1',
'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_v1']

## Event cuts
Cuts:
    # lower cut for e and mu pT
    min_tight_lepton_pT: 20
    # lower cut for tau pT
    min_tight_tau_pT: 25
    # lower cut for jet pT, jets after corrections
    min_jet_pT: 30
    min_bjet_pT: 20
    # upper cut for jet |eta| angle
    max_jet_eta: 2.5
    max_bjet_eta: 2.5
    # number of jets
    min_njets: 4
    # number of b-tagged jets
    min_nbtags: 2

## Jets' specifics
Jets:
    jet_corrector: 'ak4PFchsL1L2L3'


## Parameters for miniAODhelper class
miniAODhelper_parameters:
    using_real_data: false
    # available choices '-': none, 'L': loose, 'M': medium, 'T': tight
    b_tag_strength: 'M'